CREATE TABLE IF NOT EXISTS careers(
    careerId UUID NOT NULL PRIMARY KEY DEFAULT UUID(),
    careerCode CHAR(7) NOT NULL UNIQUE,
    careerName VARCHAR(80) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updateAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
);  