CREATE TABLE countries (
    countryId UUID NOT NULL PRIMARY KEY DEFAULT UUID(),
    country VARCHAR(50) NOT NULL UNIQUE,
    region ENUM('AF', 'AN', 'AS', 'OC', 'EU', 'AM') NOT NULL,
    zoneCode VARCHAR(50) NOT NULL,
    isoCode2 CHAR(2) NOT NULL,
    isoCode3 CHAR(3) NOT NULL,
    emojiFlag CHAR(20) NOT NULL
);

INSERT INTO countries (
    countryId, 
    country,
    region, 
    zoneCode, 
    isoCode2, 
    isoCode3, 
    emojiFlag
) VALUES
(UUID(), 'Afganistán', 'AS', '+93', 'AF', 'AFG', '🇦🇫'),
(UUID(), 'Albania', 'EU', '+355', 'AL', 'ALB', '🇦🇱'),
(UUID(), 'Alemania', 'EU', '+49', 'DE', 'DEU', '🇩🇪'),
(UUID(), 'Andorra', 'EU', '+376', 'AD', 'AND', '🇦🇩'),
(UUID(), 'Angola', 'AF', '+244', 'AO', 'AGO', '🇦🇴'),
(UUID(), 'Antigua y Barbuda', 'AM', '+1-268', 'AG', 'ATG', '🇦🇬'),
(UUID(), 'Arabia Saudita', 'AS', '+966', 'AM', 'SAU', '🇸🇦'),
(UUID(), 'Argelia', 'AF', '+213', 'DZ', 'DZA', '🇩🇿'),
(UUID(), 'Argentina', 'AM', '+54', 'AR', 'ARG', '🇦🇷'),
(UUID(), 'Armenia', 'EU', '+374', 'AM', 'ARM', '🇦🇲'),
(UUID(), 'Australia', 'OC', '+61', 'AU', 'AUS', '🇦🇺'),
(UUID(), 'Austria', 'EU', '+43', 'AT', 'AUT', '🇦🇹'),
(UUID(), 'Azerbaiyán', 'EU', '+994', 'AZ', 'AZE', '🇦🇿'),
(UUID(), 'Bahamas', 'AM', '+1-242', 'BS', 'BHS', '🇧🇸'),
(UUID(), 'Bangladés', 'AS', '+880', 'BD', 'BGD', '🇧🇩'),
(UUID(), 'Barbados', 'AM', '+1-246', 'BB', 'BRB', '🇧🇧'),
(UUID(), 'Baréin', 'AS', '+973', 'BH', 'BHR', '🇧🇭'),
(UUID(), 'Bélgica', 'EU', '+32', 'BE', 'BEL', '🇧🇪'),
(UUID(), 'Belice', 'AM', '+501', 'BZ', 'BLZ', '🇧🇿'),
(UUID(), 'Benín', 'AF', '+229', 'BJ', 'BEN', '🇧🇯'),
(UUID(), 'Bielorrusia', 'EU', '+375', 'BY', 'BLR', '🇧🇾'),
(UUID(), 'Birmania', 'AS', '+95', 'MM', 'MMR', '🇲🇲'),
(UUID(), 'Bolivia', 'AM', '+591', 'BO', 'BOL', '🇧🇴'),
(UUID(), 'Bosnia y Herzegovina', 'EU', '+387', 'BA', 'BIH', '🇧🇦'),
(UUID(), 'Botsuana', 'AF', '+267', 'BW', 'BWA', '🇧🇼'),
(UUID(), 'Brasil', 'AM', '+55', 'BR', 'BRA', '🇧🇷'),
(UUID(), 'Brunéi', 'AS', '+673', 'BN', 'BRN', '🇧🇳'),
(UUID(), 'Bulgaria', 'EU', '+359', 'BG', 'BGR', '🇧🇬'),
(UUID(), 'Burkina Faso', 'AF', '+226', 'BF', 'BFA', '🇧🇫'),
(UUID(), 'Burundi', 'AF', '+257', 'BI', 'BDI', '🇧🇮'),
(UUID(), 'Bután', 'AS', '+975', 'BT', 'BTN', '🇧🇹'),
(UUID(), 'Cabo Verde', 'AF', '+238', 'CV', 'CPV', '🇨🇻'),
(UUID(), 'Camboya', 'AS', '+855', 'KH', 'KHM', '🇰🇭'),
(UUID(), 'Camerún', 'AF', '+237', 'CM', 'CMR', '🇨🇲'),
(UUID(), 'Canadá', 'AM', '+1', 'CA', 'CAN', '🇨🇦'),
(UUID(), 'Catar', 'AS', '+974', 'QA', 'QAT', '🇶🇦'),
(UUID(), 'Chad', 'AF', '+235', 'TD', 'TCD', '🇹🇩'),
(UUID(), 'Chile', 'AM', '+56', 'CL', 'CHL', '🇨🇱'),
(UUID(), 'China', 'AS', '+86', 'CN', 'CHN', '🇨🇳'),
(UUID(), 'Chipre', 'EU', '+357', 'CY', 'CYP', '🇨🇾'),
(UUID(), 'Ciudad del Vaticano', 'EU', '+379', 'VA', 'VAT', '🇻🇦'),
(UUID(), 'Colombia', 'AM', '+57', 'CO', 'COL', '🇨🇴'),
(UUID(), 'Comoras', 'AF', '+269', 'KM', 'COM', '🇰🇲'),
(UUID(), 'Corea del Norte', 'AS', '+850', 'KP', 'PRK', '🇰🇵'),
(UUID(),'Corea del Sur','AS','+82','KR','KOR','🇰🇷'),
(UUID(),'Costa de Marfil','AF','+225','CI','CIV','🇨🇮'),
(UUID(),'Costa Rica','AM','+506','CR','CRI','🇨🇷'),
(UUID(),'Croacia','EU','+385','HR','HRV','🇭🇷'),
(UUID(),'Cuba','AM','+53','CU','CUB','🇨🇺'),
(UUID(),'Dinamarca','EU','+45','DK','DNK','🇩🇰'),
(UUID(),'Dominica','AM','+1-767','DM','DMA','🇩🇲'),
(UUID(),'Ecuador','AM','+593','EC','ECU','🇪🇨'),
(UUID(),'Egipto','AF','+20','EG','EGY','🇪🇬'),
(UUID(),'El Salvador','AM','+503','SV','SLV','🇸🇻'),
(UUID(),'Emiratos Árabes Unidos','AS','+971','AE','ARE','🇦🇪'),
(UUID(),'Eritrea','AF','+291','ER','ERI','🇪🇷'),
(UUID(),'Eslovaquia','EU','+421','SK','SVK','🇸🇰'),
(UUID(),'Eslovenia','EU','+386','SI','SVN','🇸🇮'),
(UUID(),'España','EU','+34','ES','ESP','🇪🇸'),
(UUID(),'Estados Unidos','AM','+1','US','USA','🇺🇸'),
(UUID(),'Estonia','EU','+372','EE','EST','🇪🇪'),
(UUID(),'Etiopía','AF','+251','ET','ETH','🇪🇹'),
(UUID(),'Filipinas','AS','+63','PH','PHL','🇵🇭'),
(UUID(),'Finlandia','EU','+358','FI','FIN','🇫🇮'),
(UUID(),'Fiyi','OC','+679','FJ','FJI','🇫🇯'),
(UUID(),'Francia','EU','+33','FR','FRA','🇫🇷'),
(UUID(),'Gabón','AF','+241','GA','GAB','🇬🇦'),
(UUID(),'Gambia','AF','+220','GM','GMB','🇬🇲'),
(UUID(),'Georgia','EU','+995','GE','GEO','🇬🇪'),
(UUID(),'Ghana','AF','+233','GH','GHA','🇬🇭'),
(UUID(),'Granada','AM','+1-473','GD','GRD','🇬🇩'),
(UUID(),'Grecia','EU','+30','GR','GRC','🇬🇷'),
(UUID(),'Guatemala','AM','+502','GT','GTM','🇬🇹'),
(UUID(),'Guyana','AM','+592','GY','GUY','🇬🇾'),
(UUID(),'Guinea','AF','+224','GN','GIN','🇬🇳'),
(UUID(),'Guinea-Bisáu','AF','+245','GW','GNB','🇬🇼'),
(UUID(),'Guinea Ecuatorial','AF','+240','GQ','GNQ','🇬🇶'),
(UUID(),'Haití','AM','+509','HT','HTI','🇭🇹'),
(UUID(),'Honduras','AM','+504','HN','HND','🇭🇳'),
(UUID(),'Hungría','EU','+36','HU','HUN','🇭🇺'),
(UUID(),'India','AS','+91','IN','IND','🇮🇳'),
(UUID(),'Indonesia','AS','+62','ID','IDN','🇮🇩'),
(UUID(),'Irak','AS','+964','IQ','IRQ','🇮🇶'),
(UUID(),'Irán','AS','+98','IR','IRN','🇮🇷'),
(UUID(),'Irlanda','EU','+353','IE','IRL','🇮🇪'),
(UUID(),'Islandia','EU','+354','IS','ISL','🇮🇸'),
(UUID(),'Islas Marshall','OC','+692','MH','MHL','🇲🇭'),
(UUID(),'Islas Salomón','OC','+677','SB','SLB','🇸🇧'),
(UUID(),'Israel','AS','+972','IL','ISR','🇮🇱'),
(UUID(),'Italia','EU','+39','IT','ITA','🇮🇹'),
(UUID(),'Jamaica','AM','+1-876','JM','JAM','🇯🇲'),
(UUID(),'Japón','AS','+81','JP','JPN','🇯🇵'),
(UUID(),'Jordania','AS','+962','JO','JOR','🇯🇴'),
(UUID(),'Kazajistán','EU','+7','KZ','KAZ','🇰🇿'),
(UUID(),'Kenia','AF','+254','KE','KEN','🇰🇪'),
(UUID(),'Kirguistán','EU','+996','KG','KGZ','🇰🇬'),
(UUID(),'Kiribati','OC','+686','KI','KIR','🇰🇮'),
(UUID(),'Kuwait','AS','+965','KW','KWT','🇰🇼'),
(UUID(),'Laos','AS','+856','LA','LAO','🇱🇦'),
(UUID(),'Lesoto','AF','+266','LS','LSO','🇱🇸'),
(UUID(),'Letonia','EU','+371','LV','LVA','🇱🇻'),
(UUID(),'Líbano','AS','+961','LB','LBN','🇱🇧'),
(UUID(),'Liberia','AF','+231','LR','LBR','🇱🇷'),
(UUID(),'Libia','AF','+218','LY','LBY','🇱🇾'),
(UUID(),'Liechtenstein','EU','+423','LI','LIE','🇱🇮'),
(UUID(),'Lituania','EU','+370','LT','LTU','🇱🇹'),
(UUID(),'Luxemburgo','EU','+352','LU','LUX','🇱🇺'),
(UUID(),'Madagascar','AF','+261','MG','MDG','🇲🇬'),
(UUID(),'Malasia','AS','+60','MY','MYS','🇲🇾'),
(UUID(),'Malaui','AF','+265','MW','MWI','🇲🇼'),
(UUID(),'Maldivas','AS','+960','MV','MDV','🇲🇻'),
(UUID(),'Malí','AF','+223','ML','MLI','🇲🇱'),
(UUID(),'Malta','EU','+356','MT','MLT','🇲🇹'),
(UUID(),'Marruecos','AF','+212','MA','MAR','🇲🇦'),
(UUID(),'Mauricio','AF','+230','MU','MUS','🇲🇺'),
(UUID(),'Mauritania','AF','+222','MR','MRT','🇲🇷'),
(UUID(),'México','AM','+52','MX','MEX','🇲🇽'),
(UUID(),'Micronesia','OC','+691','FM','FSM','🇫🇲'),
(UUID(),'Moldavia','EU','+373','MD','MDA','🇲🇩'),
(UUID(),'Mónaco','EU','+377','MC','MCO','🇲🇨'),
(UUID(),'Mongolia','AS','+976','MN','MNG','🇲🇳'),
(UUID(),'Montenegro','EU','+382','ME','MNE','🇲🇪'),
(UUID(),'Mozambique','AF','+258','MZ','MOZ','🇲🇿'),
(UUID(),'Namibia','AF','+264','AM','NAM','🇳🇦'),
(UUID(),'Nauru','OC','+674','NR','NRU','🇳🇷'),
(UUID(),'Nepal','AS','+977','NP','NPL','🇳🇵'),
(UUID(),'Nicaragua','AM','+505','NI','NIC','🇳🇮'),
(UUID(),'Níger','AF','+227','NE','NER','🇳🇪'),
(UUID(),'Nigeria','AF','+234','NG','NGA','🇳🇬'),
(UUID(),'Noruega','EU','+47','NO','NOR','🇳🇴'),
(UUID(),'Nueva Zelanda','OC','+64','NZ','NZL','🇳🇿'),
(UUID(),'Omán','AS','+968','OM','OMN','🇴🇲'),
(UUID(),'Países Bajos','EU','+31','NL','NLD','🇳🇱'),
(UUID(),'Pakistán','AS','+92','PK','PAK','🇵🇰'),
(UUID(),'Palaos','OC','+680','PW','PLW','🇵🇼'),
(UUID(),'Panamá','AM','+507','PA','PAN','🇵🇦'),
(UUID(),'Papúa Nueva Guinea','OC','+675','PG','PNG','🇵🇬'),
(UUID(),'Paraguay','AM','+595','PY','PRY','🇵🇾'),
(UUID(),'Perú','AM','+51','PE','PER','🇵🇪'),
(UUID(),'Polonia','EU','+48','PL','POL','🇵🇱'),
(UUID(),'Portugal','EU','+351','PT','PRT','🇵🇹'),
(UUID(),'Reino Unido','EU','+44','GB','GBR','🇬🇧'),
(UUID(),'República Centroafricana','AF','+236','CF','CAF','🇨🇫'),
(UUID(),'República Checa','EU','+420','CZ','CZE','🇨🇿'),
(UUID(),'República del Congo','AF','+242','CG','COG','🇨🇬'),
(UUID(),'República Democrática del Congo','AF','+243','CD','COD','🇨🇩'),
(UUID(),'República Dominicana','AM','+1-809, +1-829, +1-849','DO','DOM','🇩🇴'),
(UUID(),'Ruanda','AF','+250','RW','RWA','🇷🇼'),
(UUID(),'Rumanía','EU','+40','RO','ROU','🇷🇴'),
(UUID(),'Rusia','EU','+7','RU','RUS','🇷🇺'),
(UUID(),'Samoa','OC','+685','WS','WSM','🇼🇸'),
(UUID(),'San Cristóbal y Nieves','AM','+1-869','KN','KNA','🇰🇳'),
(UUID(),'San Marino','EU','+378','SM','SMR','🇸🇲'),
(UUID(),'San Vicente y las Granadinas','AM','+1-784','VC','VCT','🇻🇨'),
(UUID(),'Santa Lucía','AM','+1-758','LC','LCA','🇱🇨'),
(UUID(),'Santo Tomé y Príncipe','AF','+239','ST','STP','🇸🇹'),
(UUID(),'Senegal','AF','+221','SN','SEN','🇸🇳'),
(UUID(),'Serbia','EU','+381','RS','SRB','🇷🇸'),
(UUID(),'Seychelles','AF','+248','SC','SYC','🇸🇨'),
(UUID(),'Sierra Leona','AF','+232','SL','SLE','🇸🇱'),
(UUID(),'Singapur','AS','+65','SG','SGP','🇸🇬'),
(UUID(),'Siria','AS','+963','SY','SYR','🇸🇾'),
(UUID(),'Somalia','AF','+252','SO','SOM','🇸🇴'),
(UUID(),'Sri Lanka','AS','+94','LK','LKA','🇱🇰'),
(UUID(),'Suazilandia','AF','+268','SZ','SWZ','🇸🇿'),
(UUID(),'Sudán','AF','+249','SD','SDN','🇸🇩'),
(UUID(),'Sudán del Sur','AF','+211','SS','SSD','🇸🇸'),
(UUID(),'Suecia','EU','+46','SE','SWE','🇸🇪'),
(UUID(),'Suiza','EU','+41','CH','CHE','🇨🇭'),
(UUID(),'Surinam','AM','+597','SR','SUR','🇸🇷'),
(UUID(),'Tailandia','AS','+66','TH','THA','🇹🇭'),
(UUID(),'Tanzania','AF','+255','TZ','TZA','🇹🇿'),
(UUID(),'Tayikistán','AS','+992','TJ','TJK','🇹🇯'),
(UUID(),'Timor Oriental','OC','+670','TL','TLS','🇹🇱'),
(UUID(),'Togo','AF','+228','TG','TGO','🇹🇬'),
(UUID(),'Tonga','OC','+676','TO','TON','🇹🇴'),
(UUID(),'Trinidad y Tobago','AM','+1-868','TT','TTO','🇹🇹'),
(UUID(),'Túnez','AF','+216','TN','TUN','🇹🇳'),
(UUID(),'Turkmenistán','AS','+993','TM','TKM','🇹🇲'),
(UUID(),'Turquía','AS','+90','TR','TUR','🇹🇷'),
(UUID(),'Tuvalu','OC','+688','TV','TUV','🇹🇻'),
(UUID(),'Ucrania','EU','+380','UA','UKR','🇺🇦'),
(UUID(),'Uganda','AF','+256','UG','UGA','🇺🇬'),
(UUID(),'Uruguay','AM','+598','UY','URY','🇺🇾'),
(UUID(),'Uzbekistán','AS','+998','UZ','UZB','🇺🇿'),
(UUID(),'Vanuatu','OC','+678','VU','VUT','🇻🇺'),
(UUID(),'Venezuela','AM','+58','VE','VEN','🇻🇪'),
(UUID(),'Vietnam','AS','+84','VN','VNM','🇻🇳'),
(UUID(),'Yemen','AS','+967','YE','YEM','🇾🇪'),
(UUID(),'Yibuti','AF','+253','DJ','DJI','🇩🇯'),
(UUID(),'Zambia','AF','+260','ZM','ZMB','🇿🇲'),
(UUID(),'Zimbabue','AF','+263','ZW','ZWE','🇿🇼');