CREATE TABLE IF NOT EXISTS headquarters (
    universityHeadquartersId UUID NOT NULL PRIMARY KEY DEFAULT UUID(),
    name VARCHAR(80) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
);