CREATE TABLE IF NOT EXISTS subjects(
    subjectId UUID NOT NULL PRIMARY KEY DEFAULT UUID(),
    subjectCode CHAR(7) NOT NULL UNIQUE,
    subjectName VARCHAR(80) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updateAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
);