CREATE TABLE IF NOT EXISTS subjects(
    subjectId UUID NOT NULL NOT NULL UUID(),
    subjectCode CHAR(7) NOT NULL UNIQUE DEFAULT gen_random_code(),
    subjectName VARCHAR(80) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updateAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
);


